### ISSUE TITLE
document for propose-update that packit downloads the archive from Source(0)

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit.dev#137]
> 16:51 <jkonecny> ttomecek, last thing, could you please mention somewhere in packit.dev that propose-update will download source from Source0
> 16:51 <jkonecny> I was missing this piece of information and I thought it will create a new archive like packit srpm

**Comment by csomh** [comment]
I think we touched on this on Friday, too, and it's still not entirely clear to me, why this download is needed?

The reason this is confusing to me, is that my expectation is, that `packit` will work in the context of the repository the commands are called from. But this behaviour will break out of that context and pull in something from an external source. 

Given that, could we please clarify the reason for this behaviour and see if it still make sense and in which use cases, before documenting it? B/c it might happen that we realise that this functionality can/should be removed, and then there is no need for documentation :slightly_smiling_face:

**Comment by TomasTomecek** [comment]
https://fedoraproject.org/wiki/Packaging:SourceURL#Referencing_Source

the tarball needs to match to w/e is in the Source0 value; also `git archive` may not match the corresponding pristine upstream tarball since upstream projects may strip some of the files from the git tree
