### ISSUE TITLE
Why's URL for our documentation named "user-docs" and not just docs?

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit.dev#23]
I find `docs/` to be super-intuitive and industry-standard, `user-docs/` confuses me - are there also other documentation sites except for `user-`?

**Comment by phracek** [comment]
The idea, while I created a new structure, is to have `user-docs` for user documentation and docs for `packit API` documentation which could be added later on.
And why `packit API` documentation? I don't know if some teams, collaborators would like to use `packit` as a library.
That's the reason for `user-docs`.
Reference from `https://packit.dev/docs` could point to sphinx `packit API` documentation. Of course, if it is valid.

**Comment by TomasTomecek** [comment]
why not `docs/api/`? Much easier to remember: we also still don't know if we need API docs in future. (we'll likely do)

So can we please rename to `docs/` so it's easy to remember and navigate for everyone? One documentation site is much easier to handle rather than having multiple of them.

**Comment by TomasTomecek** [comment]
It may feel like that I am picking nits here, but my thinking is that our documentation will be accessed by people heavily so I'm very concerned about our documentation site's UX.

**Comment by phracek** [comment]
ok, let's change it into docs. As in this repo as in `packit` repo.

**Comment by TomasTomecek** [comment]
thank you

**Comment by phracek** [comment]
Fixed by #25
