### ISSUE TITLE
RFE: improve documentation about Beakerlib tests

### ISSUE THREAD

**Issue by yarda** [packit-service/packit.dev#69]
After reading several times:
https://packit.dev/testing-farm/
I still have no idea how to enable Beakerlib tests in our project.

For example the doc is at first talking about ci.fmf. Where is it located? Then it shows:
```
/test/build/smoke:
    execute:
        how: shell
        commands:
        - /usr/bin/binary --help
```
Is it content of ci.fmf? What is /test/build/smoke?

Finally it talks about 'prepare' and configuration for rhel-8 is shown (which ansible playbooks are supported?), but then it shows yaml config for Fedora. Could you add there simple working example? I am really confused and unable to setup it for our repo.

Currently we have:
https://github.com/redhat-performance/tuned repo with tests/beakerlib Beakerlib tests. Every test is in own sub-directory with own main.fmf. We want the tests to run on rhel-8 and current Fedoras. Currently I have no idea how to setup it. Any help will be appreciated.

**Comment by yarda** [comment]
Guys thanks for your hints, but even with the help of @psss and @TomasKorbar repos I am still unable to put it all together.

It seems @TomasKorbar repo doesn't have beakerlib tests (which is what I am trying to enable from the beginning) and @psss repo confused me even more. What's the 'plans' directory? Do I need it? I understand the yaml config for Packit (mostly) and I have it nearly the same as @psss, but I have no idea how to run beakerlib tests, what other FMF and YAML files are need, what their content should be and where should be such files located. 

 I have the following:
- Packit yaml config: https://github.com/redhat-performance/tuned/blob/master/.packit.yaml
- 4 basic Beakerlib tests, every test with its own FMF (FMFs were converted from Makefiles by some tool): https://github.com/redhat-performance/tuned/tree/master/tests/beakerlib
- some .fmf dir with some version information or something (I really don't know what it is good for): https://github.com/redhat-performance/tuned/tree/master/tests/beakerlib/.fmf

I am missing the point how to link it all together to run the Beakerlib tests on PR. Any help will be appreciated. Once resolved I think you could also use it as an example for other projects :)

**Comment by pvalena** [comment]
@psss TBH the behaviour of `tmt` (fmf?) it seems  rather strange.

_ _ _ _

Firstly, I had to run `tmt init`, to be able to run it, which creates `.fmf/version`. Otherwise it tracebacks  unhelpfully (and ugly). Maybe some help message, should occur (or even ask whether to create it).

On the tuned - `master`, then to make it work, I had to:
```bash
$ echo "test: ./runtest.sh" >> tests/main.fmf
$ tmt tests ls   # still no valid test, even if I create it in `tests/beakerlib`
/tests
$ mv tests/beakerlib/bz1416712-Tuned-logs-error-message-if tests
$ tmt tests ls
/tests/bz1416712-Tuned-logs-error-message-if
```
Which does not seem very intuitive IMO.

Also renaming the `main.fmf` I get:
```
$ mv tests/main.fmf tests/runtest.fmf
$ tmt tests ls
/tests/runtest
```
But maybe I've missed it has to be `main.fmf`.

And to be actually able to `run` the tests I have to create at least:
```bash
$ cat ci.fmf
discover:
    how: fmf
execute:
    how: beakerlib
$ tmt plans
Found 1 plan: /ci.
```
I had to add `discover`, because otherwise it doesn't find any tests.

Finally, I was able to run it:
```bash
$ tmt run tests --debug # note the --debug here doesn't actually do anything!
 [ . . . ]
    execute
        how: beakerlib
        result: 0 tests passed, 1 test failed
```

But to figure out what happened, I had to:
```bash
$ tmt run --debug
[ . . . ]
             > > out.log:
            ./runtest.sh: line 29: /usr/bin/rhts-environment.sh: No such file or directory
```

Finally, after a fix from the [suggested PR](https://github.com/psss/tuned/pull/1) I'm actually running the tests. But I'm still missing `tuned` apparently ([log](https://gist.github.com/pvalena/7406d2fae2ef45da20683df12b2639a4)). 
```bash
            :: [ 20:19:51 ] :: [  ERROR   ] :: rlImport: Could not find library tuned/basic
```
But I maybe packit installs it? :)

And here's [the PR]().

_ _ _ _

Note: I was running on `tmt` from [my devel branch](https://github.com/pvalena/tmt/tree/vagrant), so YMMV.

**Comment by pvalena** [comment]
@psss, @thrix did I make any mistakes or additional steps that were not needed?

**Comment by psss** [comment]
Thanks for the detailed feedback. For the future I would suggest this should be the easiest way to go:

    tmt init --base

Perhaps we should add support for common use cases:

    tmt init --template beakerlib

This would create metadata root, example plan and test which should help users to quickly start. What do you think?

**Comment by psss** [comment]
> Firstly, I had to run `tmt init`, to be able to run it, which creates `.fmf/version`. Otherwise it tracebacks unhelpfully (and ugly). Maybe some help message, should occur (or even ask whether to create it).

Hm, I don't see an ugly traceback when metadata root is not defined:

    mkdir /tmp/new
    cd /tmp/new
    tmt
    [ERROR] No metadata found in the '.' directory.

Please, file an issue describing steps to reproduce the traceback.  Thanks.

**Comment by pvalena** [comment]
@psss ah, it probably occured when `.fmf` directory did exist, but there was no `version` file. I've deleted it to revert to `master:HEAD` commit, but git does not concern itself with empty directories...

**Comment by pvalena** [comment]
> Thanks for the detailed feedback. For the future I would suggest this should be the easiest way to go:
> 
> ```
> tmt init --base
> ```

Yes, I did use that, but I don't think it's of any help, sadly.  What eluded me was:

 - I need `main.fmf`, named __exactly__ that (not `runtest.fmf`) and with `test: ....` as that identifies whether there will be tests identified. Maybe tmt could find 'invalid' `.fmf` files, and hint user what is missing to make it work?
 - I have to move the tests one level up (`tests/beakerlib/testname` ->`tests/testname`) and I still don't know why.

> Perhaps we should add support for common use cases:
> 
> ```
> tmt init --template beakerlib
> ```

Yes, seems like a good idea. Not sure about the example tests though.

> This would create metadata root, example plan and test which should help users to quickly start. What do you think?

I think users which have converted tests already do not concern themselves with examples, but wan't __those__ tests to work. Even if they have to name them one by one __[*]__. Plan (or `ci.fmf`) is good of course, but why converted tests don't contain `test: ./runtest.sh`? And can we support nested directories?
_ _ _ _
__[*]__ Could something like this work?
```yaml
discover:
    how: shell
    tests:
    - name: /tests/beakerlib
      test: ./runtest.sh
      path: /tests/beakerlib/*
execute:
    how: beakerlib
```

**Comment by psss** [comment]
I've improved the user guide in #90, please review.

**Comment by TomasTomecek** [comment]
Since the documentation is now up to date, I am going to close.

Feel free to reopen or create new issues if it's unclear.
